# -*- coding: utf-8 -*-
"""CRUD- Adryell William Gomes Nascimento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YDKHftcjReyO9mW0YpGFDJvSp28EM_rc

PRODUTO
"""

def menup():
  print("""
      Página Inicial - Produtos

    1 - Cadastrar produto
    2 - Atualizar produto
    3 - Listar produto
    4 - Excluir produto
    0 - Sair

  """)

def cadp(produtos):
  id = input("Digite o indentificador do produto: ")
  qtd = int(input("Digite a quantidade do produto no estoque: "))
  preco = input("Digite o preço do produto: ")
  preco = preco.replace(",",".")
  preco = float(preco)
  prod_novo = {"id": id, "quantidade": qtd, "preco": preco}
  produtos.append(prod_novo)

def attp(produtos):
  if not produtos:
    print("Não existe nenhum produto cadastrado")
    return
  ind = input("Digite o id do produto que deseja atualizar: ")
  for produto in produtos:
    if produto["id"] == ind:
      ask = int(input("O que você quer atualizar? 0 = quantidade, 1 = preço: "))

      if ask == 0:
        produto["quantidade"] = int(input("Digite a nova quantidade do produto: "))
      elif ask == 1:
        preco = input("Digite o novo preço do produto: ")
        preco = preco.replace(",", ".")
        produto["preco"] = float(preco)
      else:
        print("Opção Inválida")

      print("Produto atualizado")
      return

  print("Produto não encontrado")

def lisp(produtos):
    if not produtos:
        print("Nenhum produto cadastrado")
        return

    print("\nLista de Produtos:")
    for produto in produtos:
        print(f"ID: {produto['id']}, Quantidade: {produto['quantidade']}, Preço: {produto['preco']:.2f}")

def delp(produtos):
  if not produtos:
    print("Não existe nenhum produto cadastrado")
    return
  ind = input("Digite o id do produto que quer excluir: ")
  for produto in produtos:
    if produto["id"] == ind:
      ask = int(input("Tem certeza que quer apagar? 0 = sim, 1 = não: "))
      if ask == 0:
        produtos.remove(produto)
        print(f"Produto com id", {ind}, "removido")
        return
  print("Produto não encontrado")

def mainp():
  global produtos
  while True:
    menup()
    opcao = input("Digite uma opção: ")

    if opcao == "1":
      cadp(produtos)
    elif opcao == "2":
      attp(produtos)
    elif opcao == "3":
      lisp(produtos)
    elif opcao == "4":
      delp(produtos)
    elif opcao == "0":
      break
    else:
      print("Opção inválida")

"""mainp()"""

"""FORNECEDOR"""

def menuf():
  print("""
      Página inicial - Fornecedores

      1 - Cadastrar Fornecedor
      2 - Atualizar Fornecedor
      3 - Listar Fornecedor
      4 - Excluir Fornecedor
      0 - Sair

  """)

def cadf(Fornecedor):
  Nome = input("Digite o nome do fornecedor: ")
  Pfor = input("Digite o produto fornecido: ")
  Fone = input("Digite o número de telefone: (81) 9")
  End = input("Digite o endereço do fornecedor: ")
  Novf = {"Nome": Nome, "Produto": Pfor, "Telefone": Fone, "Endereço": End}
  Fornecedor.append(Novf)

def attf(Fornecedor):
  if not Fornecedor:
    print("Não existe nenhum fornecedor cadastrado")
    return
  ind = input("Digite o Nome do Fornecedor que deseja atualizar: ")
  for fornec in Fornecedor:
    if fornec["Nome"] == ind:
      ask = int(input("O que você quer atualizar? 0 = Produto, 1 = Telefone, 2 = Endereço: "))

      if ask == 0:
        fornec["Produto"] = input("Digite o produto: ")
      elif ask == 1:
        fornec["Telefone"] = input("Digite o novo número de telefone: ")
      elif ask == 2:
        fornec["Endereço"]= input("Digite o novo endereço: ")
      else:
        print("Opção Inválida")

      print("Fornecedor atualizado")
      return

  print("Fornecedor não encontrado")

def lisf(Fornecedor):
    if not Fornecedor:
        print("Nenhum Fornecedor cadastrado")
        return

    print("\nLista de Fornecedor:")
    for fornec in Fornecedor:
        print(f"Nome: {fornec['Nome']}, Produto: {fornec['Produto']}, Telefone: {fornec['Telefone']}, Endereço: {fornec['Endereço']}")

def delf(Fornecedor):
  if not Fornecedor:
    print("Não existe nenhum fornecedor cadastrado")
    return
  ind = input("Digite o nome do fornecedor que quer excluir: ")
  for fornec in Fornecedor:
    if fornec["Nome"] == ind:
      ask = int(input("Tem certeza que quer apagar? 0 = sim, 1 = não: "))
      if ask == 0:
        Fornecedor.remove(fornec)
        print(f"Fornecedor com nome", {ind}, "removido")
        return
  print("Fornecedor não encontrado")

def mainf():
  global Fornecedor
  while True:
    menuf()
    opcao = input("Digite uma opção: ")

    if opcao == "1":
      cadf(Fornecedor)
    elif opcao == "2":
      attf(Fornecedor)
    elif opcao == "3":
      lisf(Fornecedor)
    elif opcao == "4":
      delf(Fornecedor)
    elif opcao == "0":
      break
    else:
      print("Opção inválida")

"""mainf()"""

"""MOVIMENTO DE ESTOQUE"""

def menue():
  print("""
      Menu de estoque

    1 - Listar Fornecedores e produtos
    2 - Verificar estoque do produto
    3 - Comprar produto
    4 - Relatórios de vendas
    5 - Abrir outros menus
    0 - Sair

  """)

def lisfp():
  if not produtos:
        print("Nenhum produto cadastrado")

  print("\nLista de Produtos:")
  for produto in produtos:
        print(f"ID: {produto['id']}, Quantidade: {produto['quantidade']}, Preço: {produto['preco']:.2f}")

  if not Fornecedor:
        print("Nenhum Fornecedor cadastrado")

  print("\nLista de Fornecedor:")
  for fornec in Fornecedor:
        print(f"Nome: {fornec['Nome']}, Produto: {fornec['Produto']}, Telefone: {fornec['Telefone']}, Endereço: {fornec['Endereço']}")

def verp():
  if not produtos:
    print("Não existe nenhum produto cadastrado")
    return
  ind = input("Digite o Id do produto que você quer verificar o estoque: ")
  for produto in produtos:
    if produto["id"] == ind:
      if produto["quantidade"] > 0:
        print(f"O produto com id de: '{produto['id']}' tem '{produto['quantidade']}' em estoque" )
      else:
        print("Produto sem estoque")
      return
  else:
    print("Produto não encontrado")

def compp():
  if not produtos:
    print("Não existe nenhum produto cadastrado")
    return
  ask = input("Digite o id do produto: ")
  for produto in produtos:
    if produto["id"] == ask:
      qtd = int(input(f"Existem {produto['quantidade']} unidades do produto disponíveis, quanto você deseja comprar?: "))
      if qtd > int(produto["quantidade"]):
        print("Erro: Quantidade desejada maior que o estoque disponível.")
      else:
        precio = qtd * produto['preco']
        cmprdtl = {
            "id_do_produto" : produto["id"],
            "quantidade_comprada" : qtd,
            "preço_da_venda" : precio
        }

        vendas.append(cmprdtl)
        produto['quantidade'] -= qtd
        print(f"Compra realizada com sucesso! Restam {produto['quantidade']} unidades.")
        return
  print("Produto não cadastrado")

def rele():
  if not vendas:
    print("Nenhuma venda cadastrada")
    return

  print("/n" , vendas)
  for venda in vendas:
    print(f"ID do produto: {venda['id_do_produto']}, Quantidade comprada: {venda['quantidade_comprada']}, preço da venda: {venda['preço_da_venda']}")

produtos = []
Fornecedor = []
vendas = []

def maine():
  global relatorio
  while True:
    menue()
    opcao = input("Digite uma opção: ")
    if opcao == "1":
      lisfp()
    elif opcao == "2":
      verp()
    elif opcao == "3":
      compp()
    elif opcao == "4":
      rele()
    elif opcao == "5":
      ask = input("Digite qual menu voce quer abrir: 0 - Produto, 1 - Fornecedor")
      if ask == "0":
        mainp()
      elif ask == "1":
        mainf()
    elif opcao == "0":
      break
    else:
      print("Opção inválida")

maine()